import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import type { Doc, Id } from "./_generated/dataModel";
import type { MutationCtx } from "./_generated/server";

function getOrgId(identity: unknown) { const value = (identity as { orgId?: unknown; org_id?: unknown }).orgId ?? (identity as { org_id?: unknown }).org_id; return typeof value === "string" && value ? value : undefined; }
function canAccessProject(project: Doc<"projects">, identity: { subject: string; tokenIdentifier: string }) { const orgId = getOrgId(identity); return Boolean(orgId && project.clerkOrgId === orgId) || project.clerkUserId === identity.subject; }
async function requireProject(ctx: MutationCtx, projectId: Id<"projects">) { const identity = await ctx.auth.getUserIdentity(); if (!identity) throw new Error("Unauthorized"); const project = await ctx.db.get(projectId); if (!project || !canAccessProject(project, identity)) throw new Error("Project not found or access denied"); return { identity }; }

export const list = query({ args: { projectId: v.id("projects") }, handler: async (ctx, { projectId }) => { const identity = await ctx.auth.getUserIdentity(); if (!identity) return []; const project = await ctx.db.get(projectId); if (!project || !canAccessProject(project, identity)) return []; const dashboards = await ctx.db.query("dashboardConfigs").withIndex("by_projectId", (q) => q.eq("projectId", projectId)).order("asc").take(100); return Promise.all(dashboards.map(async (dashboard) => ({ ...dashboard, widgets: await ctx.db.query("dashboardWidgets").withIndex("by_dashboardId", (q) => q.eq("dashboardId", dashboard._id)).order("asc").take(100) }))); } });

export const create = mutation({ args: { projectId: v.id("projects"), name: v.string(), isDefault: v.optional(v.boolean()) }, handler: async (ctx, args) => { const { identity } = await requireProject(ctx, args.projectId); const name = args.name.trim(); if (!name) throw new Error("Dashboard name is required"); const duplicate = await ctx.db.query("dashboardConfigs").withIndex("by_projectId_and_name", (q) => q.eq("projectId", args.projectId).eq("name", name)).first(); if (duplicate) throw new Error("A dashboard with this name already exists"); const now = Date.now(); const dashboardId = await ctx.db.insert("dashboardConfigs", { projectId: args.projectId, name, isDefault: args.isDefault ?? false, createdBy: identity.subject, createdAt: now, updatedAt: now }); return dashboardId; } });

export const addWidget = mutation({ args: { projectId: v.id("projects"), dashboardId: v.id("dashboardConfigs"), widgetType: v.string() }, handler: async (ctx, args) => { await requireProject(ctx, args.projectId); const dashboard = await ctx.db.get(args.dashboardId); if (!dashboard || dashboard.projectId !== args.projectId) throw new Error("Dashboard not found"); const existing = await ctx.db.query("dashboardWidgets").withIndex("by_dashboardId", (q) => q.eq("dashboardId", args.dashboardId)).take(100); if (existing.some((widget) => widget.widgetType === args.widgetType)) throw new Error("Widget is already on this dashboard"); return ctx.db.insert("dashboardWidgets", { dashboardId: args.dashboardId, projectId: args.projectId, widgetType: args.widgetType.trim(), position: existing.length, createdAt: Date.now() }); } });

export const rename = mutation({ args: { projectId: v.id("projects"), dashboardId: v.id("dashboardConfigs"), name: v.string() }, handler: async (ctx, args) => { await requireProject(ctx, args.projectId); const dashboard = await ctx.db.get(args.dashboardId); if (!dashboard || dashboard.projectId !== args.projectId || dashboard.isDefault) throw new Error("The default dashboard cannot be renamed"); const name = args.name.trim(); if (!name) throw new Error("Dashboard name is required"); const duplicate = await ctx.db.query("dashboardConfigs").withIndex("by_projectId_and_name", (q) => q.eq("projectId", args.projectId).eq("name", name)).first(); if (duplicate && duplicate._id !== args.dashboardId) throw new Error("A dashboard with this name already exists"); await ctx.db.patch(args.dashboardId, { name, updatedAt: Date.now() }); return args.dashboardId; } });

export const reset = mutation({ args: { projectId: v.id("projects"), dashboardId: v.id("dashboardConfigs") }, handler: async (ctx, args) => { await requireProject(ctx, args.projectId); const dashboard = await ctx.db.get(args.dashboardId); if (!dashboard || dashboard.projectId !== args.projectId) throw new Error("Dashboard not found"); const widgets = await ctx.db.query("dashboardWidgets").withIndex("by_dashboardId", (q) => q.eq("dashboardId", args.dashboardId)).take(100); for (const widget of widgets) await ctx.db.delete(widget._id); await ctx.db.patch(args.dashboardId, { updatedAt: Date.now() }); return { deletedWidgets: widgets.length }; } });

export const remove = mutation({ args: { projectId: v.id("projects"), dashboardId: v.id("dashboardConfigs") }, handler: async (ctx, args) => { await requireProject(ctx, args.projectId); const dashboard = await ctx.db.get(args.dashboardId); if (!dashboard || dashboard.projectId !== args.projectId || dashboard.isDefault) throw new Error("The default dashboard cannot be deleted"); const widgets = await ctx.db.query("dashboardWidgets").withIndex("by_dashboardId", (q) => q.eq("dashboardId", args.dashboardId)).take(100); for (const widget of widgets) await ctx.db.delete(widget._id); await ctx.db.delete(args.dashboardId); return args.dashboardId; } });

export const reorderWidgets = mutation({ args: { projectId: v.id("projects"), dashboardId: v.id("dashboardConfigs"), widgetIds: v.array(v.id("dashboardWidgets")) }, handler: async (ctx, args) => { await requireProject(ctx, args.projectId); const dashboard = await ctx.db.get(args.dashboardId); if (!dashboard || dashboard.projectId !== args.projectId) throw new Error("Dashboard not found"); for (const [position, widgetId] of args.widgetIds.entries()) { const widget = await ctx.db.get(widgetId); if (!widget || widget.dashboardId !== args.dashboardId) throw new Error("Widget does not belong to dashboard"); await ctx.db.patch(widgetId, { position }); } return { updated: args.widgetIds.length }; } });
