import type { Metadata } from "next";
import { Globe2, KeyRound, Layers3, LockKeyhole, ServerCog, ShieldCheck, Siren, UserRoundCog } from "lucide-react";

export const metadata: Metadata = { title: "Security", description: "Learn how Tracify protects AI agent telemetry with encryption, project isolation, access controls, and incident response practices.", alternates: { canonical: "/security" } };

const controls = [
  { title: "Encryption", icon: LockKeyhole, summary: "TLS 1.3 in transit and AES-256 at rest.", items: ["API keys are hashed before storage.", "Plaintext project keys are shown once."] },
  { title: "Data isolation", icon: Layers3, summary: "Telemetry is scoped to the project derived from the authenticated key.", items: ["No cross-project query path.", "Cost counters remain project-specific."] },
  { title: "Data residency", icon: Globe2, summary: "EU region accounts, traces, and cache are stored in Ireland. Event processing currently runs in the United States.", items: ["Convex, Tinybird, and Redis for the EU region are hosted in Ireland.", "Queued events transit a US provider, with email, phone, card, SSN, and API-key redaction applied before they leave the EU."] },
  { title: "Access control", icon: UserRoundCog, summary: "Better Auth sessions and Convex authorization protect workspace data.", items: ["Encrypted OAuth tokens and CSRF protection.", "Organization roles are enforced at the data layer."] },
  { title: "Runtime enforcement", icon: ServerCog, summary: "Observe-first policies keep monitoring from silently changing production behavior.", items: ["Cost ceilings are evaluated server-side.", "Fail-open behavior protects production traffic."] },
  { title: "Infrastructure", icon: ShieldCheck, summary: "Convex, Tinybird, Inngest, and Redis have explicit jobs in the data path.", items: ["Durable event processing and retry semantics.", "Ephemeral cache and rate-limit state stay separate."] },
  { title: "Incident response", icon: Siren, summary: "A documented response path governs investigation and customer notification.", items: ["Affected users are notified within 72 hours.", "Security reviews run on a recurring schedule."] },
] as const;

export default function SecurityPage(){return <main className="min-h-screen bg-[#eceae3] pt-[54px] text-black"><header className="border-b border-black bg-black text-white"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[1fr_360px]"><div className="p-6 sm:p-8 md:p-10 md:py-16 lg:border-r lg:border-white/20"><div className="flex items-center gap-3 font-mono text-[9px] uppercase tracking-[0.15em] text-[#f4d44d]"><ShieldCheck className="size-4"/>Security dossier</div><h1 className="mt-10 max-w-5xl font-pixel text-[clamp(3.5rem,8vw,8rem)] leading-[0.8] tracking-[-0.08em]">Trust is a system of controls.</h1><p className="mt-8 max-w-2xl text-base leading-7 text-white/58">How agent telemetry is isolated, encrypted, governed, and investigated across the operating record.</p></div><aside className="border-t border-white/20 bg-[#f4d44d] p-6 text-black lg:border-t-0 lg:p-8"><KeyRound className="size-11" strokeWidth={1.2}/><p className="mt-24 font-pixel text-5xl leading-[0.9] tracking-[-0.06em]">Evidence for every boundary.</p><div className="mt-10 border-t border-black pt-4 font-mono text-[9px] uppercase tracking-[0.12em]">Control families / {controls.length}</div></aside></div></header><section className="border-b border-black"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[260px_1fr]"><aside className="border-black bg-[#d9d5ca] p-6 lg:border-r lg:p-8"><div className="sticky top-[86px]"><p className="font-mono text-[9px] uppercase tracking-[0.15em]">Control index</p><ol className="mt-8 divide-y divide-black border-y border-black">{controls.map((control,index)=><li key={control.title} className="flex min-h-14 items-center justify-between font-mono text-[8px] uppercase tracking-[0.1em]"><span>0{index+1}</span><span>{control.title}</span></li>)}</ol></div></aside><div>{controls.map((control,index)=>{const Icon=control.icon;return <article key={control.title} className="grid border-b border-black last:border-b-0 md:grid-cols-[100px_260px_1fr]"><div className="flex items-center justify-between border-black p-5 md:flex-col md:border-r"><span className="font-pixel text-4xl text-black/18">0{index+1}</span><Icon className="size-6" strokeWidth={1.25}/></div><div className="border-t border-black p-6 md:border-r md:border-t-0"><h2 className="font-pixel text-4xl tracking-[-0.055em]">{control.title}</h2><p className="mt-5 text-sm leading-6 text-black/62">{control.summary}</p></div><ul className="border-t border-black md:border-t-0">{control.items.map(item=><li key={item} className="flex min-h-20 items-center border-b border-black/20 px-6 text-sm last:border-b-0">{item}</li>)}</ul></article>})}</div></div></section><a href="mailto:security@tracify.tech" className="flex min-h-24 items-center justify-between bg-black px-5 font-mono text-[9px] uppercase tracking-[0.13em] text-[#f4d44d] hover:bg-[#f4d44d] hover:text-black md:px-10"><span>Report a vulnerability</span><span>security@tracify.tech</span></a></main>}
