import type { Metadata } from "next";
import { FutureAction, FuturePage } from "@/components/marketing/future19-page";

export const metadata: Metadata = { title: "Roadmap", description: "A transparent view of Tracify product delivery.", alternates: { canonical: "/roadmap" } };

const sections = [
  { status: "Shipped", code: "NOW", title: "Observe and control the runs you have today", color: "bg-[#f4d44d]", items: ["Trace and run inspection", "Cost, model, and tool analytics", "Project reports and Slack alerts", "Runtime retry, fallback, latency, and cost policies", "Python and TypeScript instrumentation", "OpenTelemetry ingestion"] },
  { status: "In progress", code: "NEXT", title: "Complete the operational foundation", color: "bg-white", items: ["Sessions and multi-agent trace views", "Search and saved filters", "Payload redaction and retention controls", "Expanded provider and framework adapters", "Public service status and supported-limit reporting"] },
  { status: "Planned", code: "LATER", title: "Evaluate and improve every release", color: "bg-[#d9d5ca]", items: ["Datasets, experiments, and CI regression checks", "Rule, LLM-judge, and human-review evaluators", "Prompt versions, playgrounds, and safe rollback", "Feedback capture and score-driven alerts", "Provider health, routing, and policy templates"] },
  { status: "Enterprise phase", code: "SCALE", title: "Deploy and govern at scale", color: "bg-black text-white", items: ["Organization roles and audit logs", "SAML/SSO and granular RBAC", "EU/US data residency", "Self-hosted Docker, Helm, and air-gapped guidance", "Migration tooling for existing observability stacks"] },
] as const;

export default function RoadmapPage() {
  return <FuturePage>
    <header className="border-b border-black"><div className="mx-auto max-w-[1240px] border-x border-black"><div className="grid md:grid-cols-[280px_1fr]"><div className="flex min-h-72 flex-col justify-between bg-[#f4d44d] p-6 md:min-h-[520px] md:p-8"><span className="font-mono text-[9px] uppercase tracking-[0.15em]">Product trajectory</span><div><span className="block font-pixel text-9xl leading-none tracking-[-0.1em]">→</span><p className="mt-4 font-mono text-[8px] uppercase leading-5 tracking-[0.12em]">Direction is public.<br/>Dates remain evidence-led.</p></div></div><div className="flex flex-col justify-between border-t border-black px-5 py-12 sm:px-8 md:border-l md:border-t-0 md:px-10 md:py-20"><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-black/45">Roadmap / 2026 onward</p><h1 className="font-pixel text-[clamp(4rem,9vw,8rem)] leading-[0.8] tracking-[-0.075em]">The work, with its uncertainty intact.</h1><p className="max-w-2xl text-base leading-7 text-black/56">What works now, what is actively moving, and what still depends on evidence from real agent teams.</p></div></div></div></header>
    <section className="border-b border-black bg-black py-8 text-white md:py-12"><div className="mx-auto max-w-[1240px] overflow-x-auto border-y border-white/20"><div className="flex min-w-[980px]">
      {sections.map((section, index) => <article key={section.status} className={`flex min-h-[560px] w-[25%] flex-col border-r border-black p-6 last:border-r-0 ${section.color}`}><div className="flex items-center justify-between font-mono text-[8px] uppercase tracking-[0.13em]"><span>0{index + 1}</span><span>{section.status}</span></div><div className="my-10 h-px bg-current opacity-30"><span className="block size-3 -translate-y-1.5 rotate-45 bg-current"/></div><strong className="font-pixel text-6xl tracking-[-0.07em]">{section.code}</strong><h2 className="mt-6 font-pixel text-3xl leading-[0.95] tracking-[-0.045em]">{section.title}</h2><ul className="mt-auto space-y-3 border-t border-current/25 pt-6">{section.items.map((item,itemIndex)=><li key={item} className="grid grid-cols-[20px_1fr] text-xs leading-5 opacity-65"><span className="font-mono text-[8px]">{itemIndex+1}</span>{item}</li>)}</ul></article>)}
    </div></div></section>
    <section className="border-b border-black bg-[#f4d44d]"><div className="mx-auto flex max-w-[1240px] flex-col gap-7 border-x border-black px-5 py-12 md:flex-row md:items-end md:justify-between md:px-10"><p className="max-w-3xl font-pixel text-5xl leading-[0.9] tracking-[-0.06em] md:text-7xl">Your failure mode can change the order.</p><FutureAction href="/contact">Tell us what is missing</FutureAction></div></section>
  </FuturePage>;
}
