import type { Metadata } from "next";
import { ArrowRight, CircleDotDashed, Flag, Gauge, Rocket } from "lucide-react";
import { FutureAction } from "@/components/marketing/future19-page";

export const metadata: Metadata = { title: "Roadmap", description: "A transparent view of Tracify product delivery.", alternates: { canonical: "/roadmap" } };

const sections = [
  { status: "Shipped", code: "NOW", title: "Observe and control the runs you have today", icon: Gauge, tone: "bg-[#f4d44d]", items: ["Trace and run inspection", "Cost, model, and tool analytics", "Project reports and Slack alerts", "Runtime retry, fallback, latency, and cost policies", "Python and TypeScript instrumentation", "OpenTelemetry ingestion"] },
  { status: "In progress", code: "NEXT", title: "Complete the operational foundation", icon: CircleDotDashed, tone: "bg-white", items: ["Sessions and multi-agent trace views", "Search and saved filters", "Payload redaction and retention controls", "Expanded provider and framework adapters", "Public service status and supported-limit reporting"] },
  { status: "Planned", code: "LATER", title: "Evaluate and improve every release", icon: Rocket, tone: "bg-[#d9d5ca]", items: ["Datasets, experiments, and CI regression checks", "Rule, LLM-judge, and human-review evaluators", "Prompt versions, playgrounds, and safe rollback", "Feedback capture and score-driven alerts", "Provider health, routing, and policy templates"] },
  { status: "Enterprise phase", code: "SCALE", title: "Deploy and govern at scale", icon: Flag, tone: "bg-black text-white", items: ["Organization roles and audit logs", "SAML/SSO and granular RBAC", "EU/US data residency", "Self-hosted Docker, Helm, and air-gapped guidance", "Migration tooling for existing observability stacks"] },
] as const;

export default function RoadmapPage(){return <main className="min-h-screen bg-[#eceae3] pt-[54px] text-black"><header className="border-b border-black"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[300px_1fr]"><aside className="flex min-h-72 flex-col justify-between border-black bg-black p-6 text-white lg:min-h-[520px] lg:border-r lg:p-8"><div className="font-mono text-[9px] uppercase tracking-[0.15em] text-white/45">Trajectory / 2026 onward</div><ArrowRight className="size-14 text-[#f4d44d]" strokeWidth={1.1}/><p className="font-mono text-[9px] uppercase leading-5 tracking-[0.12em] text-white/55">Direction is public.<br/>Dates remain evidence-led.</p></aside><div className="p-6 sm:p-8 md:p-10 md:py-16"><h1 className="max-w-6xl font-pixel text-[clamp(3.5rem,8vw,8rem)] leading-[0.8] tracking-[-0.08em]">The work, with its uncertainty intact.</h1><p className="mt-8 max-w-2xl text-base leading-7 text-black/65">What works now, what is moving, and what still depends on evidence from real agent teams.</p></div></div></header><section className="border-b border-black"><div className="mx-auto max-w-[1440px]">{sections.map((section,index)=>{const Icon=section.icon;return <article key={section.code} className={`grid border-b border-black last:border-b-0 lg:grid-cols-[160px_300px_1fr] ${section.tone}`}><div className="flex items-center justify-between border-black p-6 lg:flex-col lg:items-start lg:border-r"><span className="font-pixel text-5xl opacity-20">0{index+1}</span><Icon className="size-7" strokeWidth={1.2}/></div><div className="border-t border-black p-6 lg:border-r lg:border-t-0 lg:p-8"><p className="font-mono text-[9px] uppercase tracking-[0.14em] opacity-50">{section.status}</p><strong className="mt-6 block font-pixel text-6xl tracking-[-0.07em]">{section.code}</strong><h2 className="mt-6 font-pixel text-3xl leading-[0.92] tracking-[-0.05em]">{section.title}</h2></div><ol className="border-t border-black lg:border-t-0">{section.items.map((item,itemIndex)=><li key={item} className="grid min-h-16 grid-cols-[52px_1fr] items-center border-b border-current/25 px-5 text-sm last:border-b-0"><span className="font-mono text-[8px] opacity-40">{String(itemIndex+1).padStart(2,"0")}</span><span>{item}</span></li>)}</ol></article>})}</div></section><section className="border-b border-black bg-[#f4d44d]"><div className="mx-auto flex max-w-[1440px] flex-col gap-8 px-5 py-12 md:flex-row md:items-end md:justify-between md:px-10"><p className="max-w-4xl font-pixel text-5xl leading-[0.88] tracking-[-0.06em] md:text-7xl">Your failure mode can change the order.</p><FutureAction href="/contact">Tell us what is missing</FutureAction></div></section></main>}
