import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, CircleDot, Code2, GitBranch, Play, ShieldCheck, Sparkles } from "lucide-react";

function CtaLabel({ number, name, light = false }: { number: string; name: string; light?: boolean }) {
  return <div className={`flex items-center justify-between border-b pb-4 font-mono text-[9px] uppercase tracking-[0.17em] ${light ? "border-black/15 text-zinc-500" : "border-white/15 text-zinc-600"}`}><span>CTA {number} / {name}</span><span>Standalone direction</span></div>;
}

export function CtaExplorations() {
  return (
    <section aria-label="Call to action design explorations" className="border-t-4 border-double border-white/30 bg-black">
      <div className="border-b border-white/15 px-6 py-5 md:px-10"><div className="mx-auto flex max-w-[1240px] flex-wrap items-center justify-between gap-3"><p className="font-mono text-[10px] uppercase tracking-[0.2em]">CTA exploration gallery</p><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-zinc-600">Five original conversion directions</p></div></div>

      <section id="cta-editorial" className="relative overflow-hidden border-b border-white/15 px-6 py-20 md:px-10 md:py-28">
        <div aria-hidden="true" className="absolute inset-0 bg-[radial-gradient(circle_at_50%_52%,rgba(255,255,255,0.09),transparent_31%)]" />
        <div className="relative mx-auto max-w-[1240px]"><CtaLabel number="01" name="editorial focus" /><div className="py-20 text-center"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500">The next run starts here</p><h2 className="mx-auto mt-7 max-w-[1000px] font-pixel text-[clamp(4rem,9vw,8.5rem)] font-normal leading-[0.78] tracking-[-0.08em]">Stop guessing what your agent did.</h2><p className="mx-auto mt-7 max-w-[600px] text-lg leading-8 text-zinc-400">Get the trace, find the failure, test the fix, and release with evidence.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/sign-up" className="group inline-flex h-12 items-center gap-4 bg-white px-6 font-mono text-[10px] uppercase tracking-[0.14em] text-black">Start tracing free <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link><Link href="/demo" className="inline-flex h-12 items-center gap-3 border border-white/20 px-6 font-mono text-[10px] uppercase tracking-[0.14em]">See it on a real run <Play className="size-3" /></Link></div><p className="mt-5 font-mono text-[8px] uppercase tracking-[0.14em] text-zinc-700">No credit card · first trace in minutes</p></div></div>
      </section>

      <section id="cta-proof-panel" className="border-b border-white/15 bg-[#070707] px-6 py-20 md:px-10 md:py-24">
        <div className="mx-auto max-w-[1240px]"><CtaLabel number="02" name="proof before promise" /><div className="grid gap-px border border-white/15 bg-white/15 lg:grid-cols-[1.05fr_0.95fr]"><div className="flex flex-col justify-between bg-[#070707] p-8 md:p-12"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">A safer release is one trace away</p><h2 className="mt-6 max-w-[650px] font-pixel text-5xl font-normal leading-[0.87] tracking-[-0.068em] md:text-7xl">Turn production failures into release confidence.</h2><p className="mt-6 max-w-[530px] text-[17px] leading-8 text-zinc-400">Connect the incident, the evaluated fix, and the rollout in one operating record.</p></div><div className="mt-10 flex flex-wrap items-center gap-5"><Link href="/sign-up" className="inline-flex h-12 items-center gap-3 bg-white px-6 font-mono text-[10px] uppercase tracking-[0.14em] text-black">Create your project <ArrowRight className="size-4" /></Link><Link href="/product/lifecycle" className="font-mono text-[9px] uppercase tracking-[0.14em] text-zinc-500 hover:text-white">Explore the lifecycle</Link></div></div><div className="bg-black p-7"><div className="flex items-center justify-between border-b border-white/15 pb-4"><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-zinc-500">Release candidate / v2.4.0</p><GitBranch className="size-4 text-zinc-500" /></div><div className="grid grid-cols-2 border-b border-white/15 py-8"><div><p className="font-pixel text-7xl tracking-[-0.08em]">94.2</p><p className="mt-2 font-mono text-[8px] uppercase text-zinc-600">Quality score</p></div><div className="space-y-4">{[["Task success","96%"],["Cost target","91%"],["Policy","100%"]].map(([label,value]) => <div key={label} className="flex items-center justify-between border-b border-white/10 pb-3 font-mono text-[9px]"><span className="text-zinc-600">{label}</span><span>{value}</span></div>)}</div></div><div className="mt-6 flex items-center gap-3 bg-white p-4 font-mono text-[9px] uppercase tracking-[0.13em] text-black"><ShieldCheck className="size-4" /> Regression check passed · ready to promote</div></div></div></div>
      </section>

      <section id="cta-developer" className="border-b border-black/15 bg-[#f1efe9] px-6 py-20 text-black md:px-10 md:py-24">
        <div className="mx-auto max-w-[1240px]"><CtaLabel number="03" name="developer activation" light /><div className="grid gap-14 pt-14 lg:grid-cols-[0.84fr_1.16fr] lg:items-center"><div><div className="inline-flex items-center gap-2 border border-black/15 px-3 py-2 font-mono text-[9px] uppercase tracking-[0.14em]"><Code2 className="size-3" /> TypeScript + Python</div><h2 className="mt-7 max-w-[590px] font-pixel text-6xl font-normal leading-[0.84] tracking-[-0.07em] md:text-8xl">Your first useful trace is three lines away.</h2><p className="mt-6 max-w-[510px] text-lg leading-8 text-zinc-600">Wrap the function that runs your agent. Tracify connects every model call, tool, cost, and evaluation automatically.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/docs" className="inline-flex h-12 items-center gap-3 bg-black px-6 font-mono text-[10px] uppercase tracking-[0.14em] text-white">Open quickstart <ArrowRight className="size-4" /></Link><Link href="/sign-up" className="inline-flex h-12 items-center border border-black/20 px-6 font-mono text-[10px] uppercase tracking-[0.14em]">Get an API key</Link></div></div><div className="border border-black/20 bg-white shadow-[18px_18px_0_#111]"><div className="flex items-center justify-between border-b border-black/15 px-5 py-4 font-mono text-[9px] uppercase tracking-[0.14em] text-zinc-500"><span>agent.ts</span><span>01 / instrument</span></div><pre className="overflow-x-auto p-6 font-mono text-[13px] leading-8"><code><span className="text-zinc-400">01</span>{"  import { trace } from 'tracify'\n"}<span className="text-zinc-400">02</span>{"\n"}<span className="text-zinc-400">03</span>{"  const result = await trace(\n"}<span className="text-zinc-400">04</span>{"    'support-agent',\n"}<span className="text-zinc-400">05</span>{"    () => agent.respond(ticket)\n"}<span className="text-zinc-400">06</span>{"  )"}</code></pre><div className="flex items-center gap-2 border-t border-black/15 px-5 py-4 font-mono text-[9px] uppercase tracking-[0.13em]"><Check className="size-3" /> Trace ready to inspect</div></div></div></div>
      </section>

      <section id="cta-release-rail" className="border-b border-white/15 bg-black px-6 py-20 md:px-10 md:py-24">
        <div className="mx-auto max-w-[1240px]"><CtaLabel number="04" name="release rail" /><div className="mt-14 border-y border-white/15"><div className="grid lg:grid-cols-[1fr_auto]"><div className="border-b border-white/15 py-10 lg:border-b-0 lg:border-r lg:pr-12"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">Trace → evaluate → improve → release</p><h2 className="mt-5 max-w-[800px] font-pixel text-5xl font-normal leading-[0.88] tracking-[-0.067em] md:text-7xl">Make the next version prove itself.</h2></div><div className="flex min-w-[280px] flex-col justify-center py-10 lg:pl-12"><Link href="/sign-up" className="group flex h-14 items-center justify-between bg-white px-5 font-mono text-[10px] uppercase tracking-[0.14em] text-black">Start free <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link><Link href="/contact" className="mt-3 flex h-12 items-center justify-between border border-white/20 px-5 font-mono text-[9px] uppercase tracking-[0.14em] text-zinc-400">Talk to our team <ArrowUpRight className="size-3" /></Link></div></div><div className="grid border-t border-white/15 sm:grid-cols-4">{[["01","Capture","Every decision"],["02","Diagnose","Exact root cause"],["03","Evaluate","Measured fix"],["04","Promote","Safe rollout"]].map(([number,title,body]) => <div key={number} className="border-b border-white/15 p-5 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="font-mono text-[8px] text-zinc-700">{number}</p><p className="mt-6 font-mono text-[10px] uppercase tracking-[0.14em]">{title}</p><p className="mt-2 text-sm text-zinc-600">{body}</p></div>)}</div></div></div>
      </section>

      <section id="cta-live-signal" className="relative overflow-hidden bg-white px-6 py-20 text-black md:px-10 md:py-24">
        <div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(rgba(0,0,0,0.045)_1px,transparent_1px),linear-gradient(90deg,rgba(0,0,0,0.045)_1px,transparent_1px)] bg-[size:48px_48px]" />
        <div className="relative mx-auto max-w-[1240px]"><CtaLabel number="05" name="live signal" light /><div className="grid gap-12 pt-14 lg:grid-cols-[1fr_0.82fr] lg:items-end"><div><div className="flex items-center gap-3 font-mono text-[9px] uppercase tracking-[0.16em]"><CircleDot className="size-3" /> Production signal connected</div><h2 className="mt-7 max-w-[780px] font-pixel text-[clamp(4rem,8vw,8rem)] font-normal leading-[0.78] tracking-[-0.08em]">Give every agent a path to better.</h2><p className="mt-7 max-w-[600px] text-lg leading-8 text-zinc-600">Start with one real run. End with a change your team can explain, measure, and trust.</p></div><div className="border border-black/20 bg-[#f4f2ed] p-6"><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-zinc-500">Your workspace includes</p><div className="mt-6 space-y-4">{["Unlimited first project","Trace and cost inspection","Evaluation workflow","Release comparison"].map((item,index) => <div key={item} className="flex items-center justify-between border-b border-black/10 pb-4"><span className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.1em]"><span className="text-zinc-400">0{index + 1}</span>{item}</span><Check className="size-3" /></div>)}</div><Link href="/sign-up" className="group mt-6 flex h-14 items-center justify-between bg-black px-5 font-mono text-[10px] uppercase tracking-[0.14em] text-white">Build with evidence <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link><p className="mt-4 flex items-center gap-2 font-mono text-[8px] uppercase tracking-[0.13em] text-zinc-500"><Sparkles className="size-3" /> No credit card required</p></div></div></div>
      </section>

      <div className="border-y border-white/15 bg-black px-6 py-5 md:px-10"><div className="mx-auto flex max-w-[1240px] flex-wrap items-center justify-between gap-3"><p className="font-mono text-[10px] uppercase tracking-[0.18em]">End of CTA explorations 01–05</p><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-zinc-600">Original CTAs remain unchanged</p></div></div>
    </section>
  );
}
