import Link from "next/link";
import { ArrowUpRight, Check, Layers3, Terminal } from "lucide-react";

export function LandingExplorations() {
  return <section aria-label="Landing page concept explorations" className="border-t border-dashed border-white/30 bg-[#080808] text-white">
    <div className="border-b border-dashed border-white/20 px-6 py-4 md:px-10"><p className="mx-auto max-w-[1240px] font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">Developer proof / additive concept exploration</p></div>
    <section id="concept-readme" className="border-y border-white/10 bg-white px-6 py-24 text-black md:px-10 md:py-32"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[0.78fr_1.22fr] lg:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">Quickstart that earns trust</p><h2 className="mt-5 max-w-[510px] font-pixel text-5xl font-normal leading-[.91] tracking-[-.065em] md:text-7xl">Install once. See the whole run.</h2><p className="mt-6 max-w-[440px] text-[16px] leading-7 text-zinc-600">Use the published SDK contract, then let the trace viewer connect model calls, tools, retries, cost, and quality evidence.</p><Link href="/docs" className="mt-8 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.14em] underline underline-offset-8">Read the documentation <ArrowUpRight className="size-3" /></Link></div><div className="overflow-hidden border border-black/20 bg-[#f5f5f2] font-mono"><div className="flex items-center justify-between border-b border-black/15 px-5 py-4 text-[10px] uppercase tracking-[0.14em] text-zinc-500"><span>README.md</span><span>Quick start</span></div><div className="grid gap-px bg-black/15 md:grid-cols-[0.95fr_1.05fr]"><div className="bg-[#f5f5f2] p-6"><div className="flex items-center gap-3"><Terminal className="size-4" /><p className="text-xs uppercase tracking-[0.14em]">1. Instrument</p></div><pre className="mt-7 overflow-x-auto text-[13px] leading-7 text-zinc-700">{`npm install 5to1r\n\nimport { traceAgent } from '5to1r'\n\nconst tracedRun = traceAgent(run)`}</pre></div><div className="bg-white p-6"><div className="flex items-center gap-3"><Check className="size-4" /><p className="text-xs uppercase tracking-[0.14em]">2. Inspect</p></div><p className="mt-7 text-[15px] leading-7 text-zinc-600">The run arrives with model, tools, retries, cost, and quality result already linked.</p></div></div></div></div></section>
    <section id="concept-lifecycle" className="px-6 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1240px]"><div className="flex items-end justify-between gap-6 border-b border-white/15 pb-8"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">Connected platform</p><h2 className="mt-5 max-w-[650px] font-pixel text-5xl font-normal leading-[.91] tracking-[-.065em] md:text-7xl">Every signal belongs to the same improvement loop.</h2></div><Layers3 className="size-7 text-zinc-500" /></div></div></section>
  </section>;
}
