import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getDoc, getDocs } from "@/lib/markdoc-docs";
import { MarkdocDoc } from "@/components/docs/markdoc-doc";
import { FuturePage } from "@/components/marketing/future19-page";

export function generateStaticParams() { return getDocs().map((doc) => ({ slug: [doc.slug] })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string[] }> }): Promise<Metadata> { const doc = getDoc((await params).slug?.[0] ?? ""); return doc ? { title: doc.title, description: doc.description, alternates: { canonical: `/docs/${doc.slug}` } } : {}; }
export default async function DocsArticlePage({ params }: { params: Promise<{ slug: string[] }> }) { const doc = getDoc((await params).slug?.[0] ?? ""); if (!doc) notFound(); const docs = getDocs(); const sections = [...new Set(docs.map((item) => item.section))]; return <FuturePage><div className="min-h-screen bg-[#f3f2ed] text-black"><div className="mx-auto grid max-w-[1240px] border-x border-b border-black lg:grid-cols-[230px_1fr]"><aside className="border-b border-black bg-[#f4d44d] p-6 lg:sticky lg:top-0 lg:h-screen lg:self-start lg:overflow-y-auto lg:border-b-0 lg:border-r"><p className="font-mono text-[9px] uppercase tracking-[.14em]">Tracify docs</p><a href="/docs" className="mt-8 block font-mono text-[10px] uppercase tracking-[.08em] underline underline-offset-4">Overview</a><nav className="mt-8 flex flex-col gap-7">{sections.map((section) => <div key={section}><p className="border-t border-black/30 pt-3 font-mono text-[9px] uppercase tracking-[.12em] text-black/50">{section}</p><div className="mt-3 flex flex-col gap-3">{docs.filter((item) => item.section === section).map((item) => <a key={item.slug} href={`/docs/${item.slug}`} className={`font-mono text-[10px] uppercase tracking-[.08em] ${item.slug === doc.slug ? "underline underline-offset-4" : "text-black/55 hover:text-black"}`}>{item.title}</a>)}</div></div>)}</nav></aside><main className="min-w-0 bg-[#f3f2ed] p-6 md:p-14"><p className="font-mono text-[9px] uppercase tracking-[.14em] text-black/45">{doc.section} / guide {String(doc.order).padStart(2,"0")}</p><h1 className="mt-8 max-w-3xl font-pixel text-[clamp(3.5rem,7vw,6.5rem)] leading-[.84] tracking-[-.07em]">{doc.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-black/60">{doc.description}</p><div className="mt-14 border-t border-black pt-10"><MarkdocDoc content={doc.content} /></div></main></div></div></FuturePage>; }
