import type { Metadata } from "next";
import { Database, Eye, LockKeyhole, SlidersHorizontal } from "lucide-react";

export const metadata: Metadata = { title: "Privacy policy", description: "Tracify privacy policy and information about how we handle data.", alternates: { canonical: "/privacy" } };

const sections = [
  { title: "Overview", body: "This policy explains how Tracify collects, uses, and safeguards information when you use the agent observability platform.", bullets: [] },
  { title: "Collection", body: "We collect information you provide directly and technical data generated through use of the platform.", bullets: ["Account information such as name, email, and organization.", "Telemetry sent through the SDK, including spans, tool calls, and model logs.", "Usage data such as browser type and platform interaction."] },
  { title: "Use", body: "Collected data is used to provide, maintain, protect, and improve the service.", bullets: ["Process and visualize agent telemetry.", "Provide cost and performance analytics.", "Send requested system alerts and notifications."] },
  { title: "Protection", body: "Telemetry is encrypted in transit and at rest. Access is limited to authorized people and systems needed to provide the service.", bullets: [] },
  { title: "Control", body: "Questions and privacy requests can be sent directly to privacy@tracify.tech.", bullets: [] },
] as const;

export default function PrivacyPage(){return <main className="min-h-screen bg-[#eceae3] pt-[54px] text-black"><header className="border-b border-black"><div className="mx-auto max-w-[1440px]"><div className="grid lg:grid-cols-[1fr_360px]"><div className="p-6 sm:p-8 md:p-10 md:py-16 lg:border-r lg:border-black"><div className="flex items-center gap-3 font-mono text-[9px] uppercase tracking-[0.15em] text-black/45"><Database className="size-4"/>Data lifecycle record</div><h1 className="mt-10 max-w-6xl font-pixel text-[clamp(3.5rem,8vw,8rem)] leading-[0.8] tracking-[-0.08em]">What enters. What stays. What leaves.</h1><p className="mt-8 max-w-2xl text-base leading-7 text-black/62">The policy arranged around the lifecycle of information rather than a wall of legal prose.</p></div><aside className="border-t border-black bg-[#f4d44d] p-6 lg:border-t-0 lg:p-8"><p className="font-mono text-[9px] uppercase tracking-[0.15em]">Effective / 16.05.26</p><div className="mt-20 space-y-6">{[{icon:Eye,label:"Collection"},{icon:LockKeyhole,label:"Protection"},{icon:SlidersHorizontal,label:"Control"}].map(item=>{const Icon=item.icon;return <div key={item.label} className="flex items-center gap-4 border-b border-black pb-5"><Icon className="size-6" strokeWidth={1.2}/><span className="font-pixel text-3xl">{item.label}</span></div>})}</div></aside></div></div></header><section className="border-b border-black"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[260px_1fr]"><aside className="border-black bg-black p-6 text-white lg:border-r lg:p-8"><div className="sticky top-[86px]"><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-white/45">Policy index</p><ol className="mt-8 divide-y divide-white/20 border-y border-white/20">{sections.map((section,index)=><li key={section.title} className="flex min-h-14 items-center justify-between font-mono text-[8px] uppercase tracking-[0.1em]"><span>0{index+1}</span><span>{section.title}</span></li>)}</ol></div></aside><div>{sections.map((section,index)=><article key={section.title} className="grid border-b border-black last:border-b-0 md:grid-cols-[100px_240px_1fr]"><div className={`flex items-center justify-center border-black p-5 font-pixel text-5xl text-black/20 md:border-r ${index===1?"bg-[#f4d44d]":""}`}>0{index+1}</div><h2 className="border-t border-black p-6 font-pixel text-4xl tracking-[-0.055em] md:border-r md:border-t-0">{section.title}</h2><div className="border-t border-black p-6 text-sm leading-7 text-black/62 md:border-t-0"><p>{section.body}</p>{section.bullets.length?<ul className="mt-5 list-square space-y-2 pl-5">{section.bullets.map(item=><li key={item}>{item}</li>)}</ul>:null}</div></article>)}</div></div></section><a href="mailto:privacy@tracify.tech" className="flex min-h-24 items-center justify-between bg-[#f4d44d] px-5 font-mono text-[9px] uppercase tracking-[0.13em] md:px-10"><span>Privacy questions</span><span>privacy@tracify.tech</span></a></main>}
