import Link from "next/link";
import { ArrowRight, BookOpen, Braces, Check, Code2, Gauge, Layers3, ShieldCheck, Terminal } from "lucide-react";
import { getDocs } from "@/lib/markdoc-docs";
import { DocsSearch } from "@/components/docs/docs-search";
import { FuturePage } from "@/components/marketing/future19-page";

export const metadata = { title: "Documentation", description: "Install the SDK, instrument an agent, and inspect the execution record.", alternates: { canonical: "/docs" } };

const productAreas = [
  ["Observability", "Trace runs, sessions, tools, costs, and failures.", "observability", Gauge],
  ["Prompt operations", "Version, resolve, cache, and connect prompts to traces.", "prompts", Braces],
  ["Evaluation", "Turn production evidence into measurable release gates.", "evaluation", Check],
  ["Platform", "Use APIs, exports, datasets, and deployment controls.", "api-platform", Layers3],
] as const;

const quickstarts = [
  ["Start tracing", "Send your first useful run in under five minutes.", "quickstart", Terminal],
  ["TypeScript SDK", "Instrument Node.js, Next.js, or worker workloads.", "typescript", Code2],
  ["Python SDK", "Add tracing to a Python agent with a small decorator.", "python", BookOpen],
] as const;

export default function DocsRootPage() {
  const docs = getDocs();
  const searchDocs = docs.map(({ slug, title, description }) => ({ slug, title, description }));
  const sections = [...new Set(docs.map((doc) => doc.section))];
  const sectionDocs = (section: string) => docs.filter((doc) => doc.section === section);
  return <FuturePage><div className="min-h-screen bg-[#f3f2ed] text-black">
    <div className="mx-auto max-w-[1440px] border-x border-b border-black"><div className="flex items-center justify-between gap-4 px-5 py-3 font-mono text-[9px] uppercase tracking-[.13em] sm:px-8"><span className="text-black/45">Tracify / Documentation</span><div className="flex gap-4"><Link href="/integrations" className="hover:underline">Integrations</Link><Link href="/status" className="hover:underline">System status</Link><Link href="/contact" className="hover:underline">Talk to us</Link></div></div></div>
    <div className="mx-auto grid max-w-[1440px] border-x border-b border-black lg:grid-cols-[230px_minmax(0,1fr)_190px]">
      <aside className="hidden border-r border-black bg-[#eceae3] p-6 lg:block"><div className="sticky top-6"><p className="font-pixel text-2xl tracking-[-.06em]">tracify docs</p><Link href="/docs" className="mt-10 block border-l-2 border-black py-2 pl-3 font-mono text-[10px] uppercase tracking-[.1em]">Overview</Link><p className="mt-10 font-mono text-[9px] uppercase tracking-[.14em] text-black/45">Get started</p><nav className="mt-4 space-y-3">{quickstarts.map(([title, , slug]) => <Link key={slug} href={`/docs/${slug}`} className="block text-sm leading-5 text-black/65 hover:text-black">{title}</Link>)}</nav><p className="mt-10 font-mono text-[9px] uppercase tracking-[.14em] text-black/45">Product areas</p><nav className="mt-4 space-y-3">{productAreas.map(([title, , slug]) => <Link key={slug} href={`/docs/${slug}`} className="block text-sm leading-5 text-black/65 hover:text-black">{title}</Link>)}</nav><p className="mt-10 font-mono text-[9px] uppercase tracking-[.14em] text-black/45">Reference</p><nav className="mt-4 space-y-3">{["api", "public-api", "integrations", "self-hosting"].map((slug) => { const doc = docs.find((item) => item.slug === slug); return doc ? <Link key={slug} href={`/docs/${slug}`} className="block text-sm leading-5 text-black/65 hover:text-black">{doc.title}</Link> : null; })}</nav></div></aside>
      <main className="min-w-0 bg-[#f3f2ed]">
        <div className="border-b border-black p-5 md:p-10"><DocsSearch docs={searchDocs} /><p className="mt-12 font-mono text-[9px] uppercase tracking-[.15em] text-black/45">Documentation / overview</p><h1 className="mt-6 max-w-3xl font-pixel text-[clamp(3.5rem,8vw,7.5rem)] leading-[.82] tracking-[-.08em]">Build agents<br/>you can explain.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-black/62">Trace the decisions, measure the outcomes, and promote the versions that prove themselves in production.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/docs/quickstart" className="inline-flex min-h-12 items-center gap-3 bg-black px-5 font-mono text-[9px] uppercase tracking-[.13em] text-white hover:bg-[#f4d44d] hover:text-black">Start tracing <ArrowRight className="size-4" /></Link><Link href="/demo" className="inline-flex min-h-12 items-center gap-3 border border-black px-5 font-mono text-[9px] uppercase tracking-[.13em] hover:bg-white">Open example project <ArrowRight className="size-4" /></Link></div></div>
        <section id="get-started" className="border-b border-black p-5 md:p-10"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-[9px] uppercase tracking-[.14em] text-black/45">Get started</p><h2 className="mt-3 font-pixel text-5xl leading-[.86] tracking-[-.07em]">Choose your first job.</h2></div><Terminal className="hidden size-7 md:block" /></div><div className="mt-8 grid border-l border-t border-black sm:grid-cols-3">{quickstarts.map(([title, body, slug, Icon]) => <Link key={slug} href={`/docs/${slug}`} className="group min-h-52 border-b border-r border-black bg-white p-5 hover:bg-[#f4d44d]"><Icon className="size-5" strokeWidth={1.4} /><h3 className="mt-12 font-pixel text-3xl leading-none tracking-[-.05em]">{title}</h3><p className="mt-3 text-sm leading-6 text-black/58">{body}</p><span className="mt-6 inline-flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.12em]">Open guide <ArrowRight className="size-3" /></span></Link>)}</div></section>
        <section id="product-areas" className="border-b border-black p-5 md:p-10"><p className="font-mono text-[9px] uppercase tracking-[.14em] text-black/45">Product areas</p><h2 className="mt-3 font-pixel text-5xl leading-[.86] tracking-[-.07em]">One operating record.<br/>Four ways to use it.</h2><div className="mt-8 grid border-l border-t border-black sm:grid-cols-2">{productAreas.map(([title, body, slug, Icon]) => <Link key={slug} href={`/docs/${slug}`} className="group min-h-56 border-b border-r border-black bg-white p-6 hover:bg-[#f4d44d]"><div className="flex items-center justify-between"><Icon className="size-5" strokeWidth={1.4} /><span className="font-mono text-[9px] text-black/35">→</span></div><h3 className="mt-16 font-pixel text-4xl leading-none tracking-[-.06em]">{title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-black/58">{body}</p></Link>)}</div></section>
        <section id="all-guides" className="p-5 md:p-10"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-[9px] uppercase tracking-[.14em] text-black/45">All guides</p><h2 className="mt-3 font-pixel text-5xl leading-[.86] tracking-[-.07em]">Read by intent.</h2></div><span className="font-mono text-[9px] uppercase tracking-[.12em] text-black/45">{docs.length} chapters</span></div><div className="mt-8 space-y-10">{sections.map((section) => <div key={section}><div className="flex items-center gap-3 border-b border-black pb-3"><span className="size-2 bg-[#f4d44d]" /><h3 className="font-mono text-[10px] uppercase tracking-[.14em]">{section}</h3><span className="font-mono text-[9px] text-black/35">{sectionDocs(section).length}</span></div><div className="divide-y divide-black/20">{sectionDocs(section).map((doc) => <Link key={doc.slug} href={`/docs/${doc.slug}`} className="group grid gap-2 py-4 sm:grid-cols-[1fr_1.4fr_auto] sm:items-center sm:gap-6"><span className="font-pixel text-2xl tracking-[-.04em] group-hover:underline">{doc.title}</span><span className="text-sm leading-6 text-black/55">{doc.description}</span><ArrowRight className="hidden size-4 sm:block" /></Link>)}</div></div>)}</div></section>
      </main>
      <aside className="hidden border-l border-black bg-[#eceae3] p-5 xl:block"><div className="sticky top-6"><p className="font-mono text-[9px] uppercase tracking-[.14em] text-black/45">On this page</p><nav className="mt-5 space-y-4 border-l border-black/20 pl-4 text-sm"><a href="#get-started" className="block hover:underline">Get started</a><a href="#product-areas" className="block hover:underline">Product areas</a><a href="#all-guides" className="block hover:underline">All guides</a></nav><div className="mt-20 border-t border-black pt-5"><ShieldCheck className="size-5" /><p className="mt-4 font-pixel text-2xl leading-none tracking-[-.05em]">Need a hand?</p><p className="mt-3 text-sm leading-6 text-black/55">Bring a run you do not trust and we will map the next useful signal.</p><Link href="/contact?intent=trace-clinic" className="mt-5 inline-flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.12em] underline underline-offset-4">Talk to us <ArrowRight className="size-3" /></Link></div></div></aside>
    </div>
  </div></FuturePage>;
}
